[package]
name = "spelling_trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
url = { version = "2.4.1"}

[dev-dependencies]
lazy_static = "1.4.0"
